/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface FooterComponent {
    'company': string;
    'logo': string;
  }
}

declare global {


  interface HTMLFooterComponentElement extends Components.FooterComponent, HTMLStencilElement {}
  var HTMLFooterComponentElement: {
    prototype: HTMLFooterComponentElement;
    new (): HTMLFooterComponentElement;
  };
  interface HTMLElementTagNameMap {
    'footer-component': HTMLFooterComponentElement;
  }
}

declare namespace LocalJSX {
  interface FooterComponent extends JSXBase.HTMLAttributes<HTMLFooterComponentElement> {
    'company'?: string;
    'logo'?: string;
  }

  interface IntrinsicElements {
    'footer-component': FooterComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


